"""Static report labels per locale (the program body language is the agent's)."""

LABEL_KEYS = (
    "report_title",
    "athlete",
    "goal",
    "program_version",
    "generated_on",
    "adaptation_reason",
    "references",
    "evidence_note",
    "season_title",
    "season_ref",
    "season_events",
    "season_phases",
    "season_taper",
    "season_tests",
    "week",
    "load_title",
    "load_last_week",
    "load_external",
    "load_monotony",
    "load_strain",
    "load_fitness",
    "load_summary",
    "response_title",
    "response_rate",
    "response_prior",
    "response_adherence",
    "response_tolerance",
    "response_caveats",
    "per_week",
    "not_available",
    "tol_higher_fatigue",
    "tol_lower_fatigue",
    "tol_no_direction",
)

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "report_title": "Training Report",
        "athlete": "Athlete",
        "goal": "Goal",
        "program_version": "Program version",
        "generated_on": "Generated on",
        "adaptation_reason": "Adaptation reason",
        "references": "References",
        "evidence_note": "Evidence grades: ★★★★★ strong … ★☆☆☆☆ expert opinion.",
        "season_title": "Season overview",
        "season_ref": "Season context",
        "season_events": "Events",
        "season_phases": "Phase timeline",
        "season_taper": "Taper weeks",
        "season_tests": "Test weeks",
        "week": "week",
        "load_title": "Load trends",
        "load_last_week": "Last-week load",
        "load_external": "external",
        "load_monotony": "Monotony",
        "load_strain": "Strain",
        "load_fitness": "Fitness/fatigue trend",
        "load_summary": "Load (last week)",
        "response_title": "Response summary",
        "response_rate": "Measured goal rate",
        "response_prior": "population prior (no measured rate yet)",
        "response_adherence": "Adherence by quality",
        "response_tolerance": "Volume tolerance",
        "response_caveats": "Caveats",
        "per_week": "wk",
        "not_available": "n/a",
        "tol_higher_fatigue": "higher volume tracks higher fatigue",
        "tol_lower_fatigue": "higher volume tracks lower fatigue",
        "tol_no_direction": "no clear volume/fatigue direction",
    },
    "fr": {
        "report_title": "Rapport d'entraînement",
        "athlete": "Athlète",
        "goal": "Objectif",
        "program_version": "Version du programme",
        "generated_on": "Généré le",
        "adaptation_reason": "Raison de l'adaptation",
        "references": "Références",
        "evidence_note": "Niveaux de preuve : ★★★★★ solide … ★☆☆☆☆ avis d'expert.",
        "season_title": "Vue de saison",
        "season_ref": "Contexte de saison",
        "season_events": "Événements",
        "season_phases": "Chronologie des phases",
        "season_taper": "Semaines d'affûtage",
        "season_tests": "Semaines de test",
        "week": "semaine",
        "load_title": "Tendances de charge",
        "load_last_week": "Charge de la dernière semaine",
        "load_external": "externe",
        "load_monotony": "Monotonie",
        "load_strain": "Contrainte",
        "load_fitness": "Tendance forme/fatigue",
        "load_summary": "Charge (dernière semaine)",
        "response_title": "Synthèse de la réponse",
        "response_rate": "Progression mesurée de l'objectif",
        "response_prior": "a priori de population (pas encore de taux mesuré)",
        "response_adherence": "Observance par qualité",
        "response_tolerance": "Tolérance au volume",
        "response_caveats": "Réserves",
        "per_week": "sem.",
        "not_available": "n/d",
        "tol_higher_fatigue": "plus de volume associé à plus de fatigue",
        "tol_lower_fatigue": "plus de volume associé à moins de fatigue",
        "tol_no_direction": "pas de direction volume/fatigue nette",
    },
    "es": {
        "report_title": "Informe de entrenamiento",
        "athlete": "Atleta",
        "goal": "Objetivo",
        "program_version": "Versión del programa",
        "generated_on": "Generado el",
        "adaptation_reason": "Motivo de la adaptación",
        "references": "Referencias",
        "evidence_note": "Niveles de evidencia: ★★★★★ sólido … ★☆☆☆☆ opinión experta.",
        "season_title": "Resumen de temporada",
        "season_ref": "Contexto de temporada",
        "season_events": "Eventos",
        "season_phases": "Cronología de fases",
        "season_taper": "Semanas de afinamiento",
        "season_tests": "Semanas de test",
        "week": "semana",
        "load_title": "Tendencias de carga",
        "load_last_week": "Carga de la última semana",
        "load_external": "externa",
        "load_monotony": "Monotonía",
        "load_strain": "Tensión",
        "load_fitness": "Tendencia forma/fatiga",
        "load_summary": "Carga (última semana)",
        "response_title": "Resumen de respuesta",
        "response_rate": "Ritmo medido del objetivo",
        "response_prior": "a priori poblacional (aún sin ritmo medido)",
        "response_adherence": "Adherencia por cualidad",
        "response_tolerance": "Tolerancia al volumen",
        "response_caveats": "Advertencias",
        "per_week": "sem.",
        "not_available": "n/d",
        "tol_higher_fatigue": "más volumen asociado a más fatiga",
        "tol_lower_fatigue": "más volumen asociado a menos fatiga",
        "tol_no_direction": "sin dirección clara volumen/fatiga",
    },
}
