"""Deterministic sports science engine (no LLM, no I/O).

Public API re-exports. Agents call these functions as tools; they never
compute training numbers themselves.
"""

from performance_agent.engine.endurance import pace_s_per_km, riegel_predict
from performance_agent.engine.feasibility import (
    BodycompFeasibility,
    FeasibilityResult,
    TrainingAge,
    bodycomp_feasibility,
    endurance_feasibility,
    hypertrophy_feasibility,
    strength_feasibility,
)
from performance_agent.engine.load import (
    acute_chronic_ratio,
    session_rpe_load,
    weekly_loads,
)
from performance_agent.engine.nutrition import (
    EnergyTarget,
    bmr_mifflin_st_jeor,
    prescribe_energy_target,
    tdee_from_bmr,
)
from performance_agent.engine.periodization import (
    BlockWeek,
    InseasonWeek,
    PeakingWeek,
    UndulatingSession,
    WeekLoad,
    build_block_periodization,
    build_inseason_week,
    build_strength_peaking,
    build_undulating_week,
    build_weekly_waves,
)
from performance_agent.engine.season import (
    SeasonEvent,
    SeasonModality,
    SeasonSegment,
    plan_season,
    recommend_taper_length,
)
from performance_agent.engine.strength import (
    ProgressionDecision,
    TopSetBackoff,
    WaveStep,
    WeeklySetTargets,
    double_progression,
    load_for_percentage,
    one_rm_brzycki,
    one_rm_epley,
    one_rm_lombardi,
    one_rm_wathan,
    percentage_for_reps_rir,
    reps_for_percentage_rir,
    rir_from_rpe,
    top_set_backoff,
    warmup_scheme,
    wave_loading,
    weekly_set_targets,
)

__all__ = [
    "BlockWeek",
    "BodycompFeasibility",
    "EnergyTarget",
    "FeasibilityResult",
    "InseasonWeek",
    "PeakingWeek",
    "ProgressionDecision",
    "SeasonEvent",
    "SeasonModality",
    "SeasonSegment",
    "TopSetBackoff",
    "TrainingAge",
    "UndulatingSession",
    "WaveStep",
    "WeekLoad",
    "WeeklySetTargets",
    "acute_chronic_ratio",
    "bmr_mifflin_st_jeor",
    "bodycomp_feasibility",
    "build_block_periodization",
    "build_inseason_week",
    "build_strength_peaking",
    "build_undulating_week",
    "build_weekly_waves",
    "double_progression",
    "endurance_feasibility",
    "hypertrophy_feasibility",
    "load_for_percentage",
    "one_rm_brzycki",
    "one_rm_epley",
    "one_rm_lombardi",
    "one_rm_wathan",
    "pace_s_per_km",
    "percentage_for_reps_rir",
    "plan_season",
    "prescribe_energy_target",
    "recommend_taper_length",
    "reps_for_percentage_rir",
    "riegel_predict",
    "rir_from_rpe",
    "session_rpe_load",
    "strength_feasibility",
    "tdee_from_bmr",
    "top_set_backoff",
    "warmup_scheme",
    "wave_loading",
    "weekly_loads",
    "weekly_set_targets",
]
